version: '2'
services:
  ui:
    depends_on:
      - server
    container_name: speedtest-ui-prod
    build: ./ui
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
  server:
    depends_on:
      - db
    container_name: speedtest-server-prod
    build: ./server
    restart: always
    ports:
      - "3000:3000"
    env_file: ./server/.env.production
  db:
    container_name: speedtest-db-prod
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: ./db/.env.production
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
